# !!! Development only !!!
services:
  media-storage:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cloudimny
      POSTGRES_PASSWORD: cloudimny
      POSTGRES_DB: cloudimny
    volumes:
      - sql_data:/var/lib/postgresql/data

volumes:
  minio_data:
  sql_data:
